### ISSUE TITLE
How to configure navigation and footer

### ISSUE THREAD

**Issue by khawarizmus** [unjs/undocs#104]
### Describe the change

Currently the footer specifies that `packagename` is part of `Unjs Ecosystem` in the footer and both the footer and header have a twitter (X) icon which points to the official Unjs twitter profile.

I think the documentation should mention how to customise these. I also noticed that the possible `heroLinks` are not documented. 

### Additional information

- [X] Would you be willing to help?

**Comment by pi0** [comment]
> I think the documentation should mention how to customise these. 

Hi and thanks for your interest. But currently, this is an internal tool designed for UnJS org. It is not open for general use and customization but we have prepared structure for this in the future...
