### ISSUE TITLE
Nuxt UI Pro License required?

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/undocs#110]
### Describe the change

Is it possible to use undocs without a nuxt ui pro license? I think it would be good to add some documentation around it.

(Background: I'm considering using undocs for the documentation of a few of my projects https://github.com/apollo-server-integrations/apollo-server-integration-h3, https://github.com/tobiasdiez/nuxt-graphql-server, https://github.com/tobiasdiez/storybook-vue-addon. But if I have to pay 200 Euro for the pro version, then I'll probably go with a simpler solution for the docs.)

### Additional information

- [ ] Would you be willing to help?

**Comment by pi0** [comment]
Hi. thanks for your interest ❤️ 

Undocs is currently only meant for usage in the unjs ecosystem and got a license for it. It is too early for me to promise anything on behalf of Nuxt UI Pro but it is likely it will be open/free for all open source docs once reusable.

**Comment by tobiasdiez** [comment]
Make sense, thanks for the clarification!
