### ISSUE TITLE
Dev server starts really slow

### ISSUE THREAD

**Issue by aquapi** [unjs/undocs#151]
### Environment

- Ubuntu 24.04
- Node 21.7.3
- Bun 1.1.31

### Reproduction

`bun dev`

### Describe the bug

![image](https://github.com/user-attachments/assets/f22356b4-6ce2-4d43-80ca-b5d946a18ab3)

**Comment by pi0** [comment]
I know and i'm so sad about perf too, sorry :( Nothing doable in undocs level -- longer term tracker #$51
