### ISSUE TITLE
Syntax highlights broken with cf deploys

### ISSUE THREAD

**Issue by pi0** [unjs/undocs#40]
why? no ideas!

**Comment by cpreston321** [comment]
https://github.com/nuxt/content/issues/2531

**Comment by cpreston321** [comment]
Another reason is that we use custom <ProseCode> components that don't render the highlighting which I will open a PR here soon to support `unjs/docs` custom component.

**Comment by Barbapapazes** [comment]
> Could be related: https://github.com/nuxt/content/issues/2531

I'm trying to know why. Need a little more time to investigate. It's related to a dependency of one of a Nuxt package.

**Comment by pi0** [comment]
now we only have issues with tabs ~> https://github.com/unjs/undocs/issues/45
