### ISSUE TITLE
Add a way to configure global components

### ISSUE THREAD

**Issue by cpreston321** [unjs/undocs#49]
### Describe the feature

Need a way to expose components to docs but we enable them through docs.config

Example: -> https://github.com/nuxt-ui-pro/docs/blob/dbe80b2d4f2ee1c7065311f51dc18f0314794dd3/nuxt.config.ts#L13-L17

---

Initial thought bc I was working on Nitro docs and buttons did not work and I just wanted to use the Nuxt/UI Buttons and since they are not global you can't use them. 

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
More dicussion context in https://github.com/unjs/undocs/pull/50

since undocs is a minimal documentation generator tool, if we want to expose components, we shall directly make a global component in undocs like `::button`
