### ISSUE TITLE
Light Mode is kinda off

### ISSUE THREAD

**Issue by cpreston321** [unjs/undocs#59]
### Environment

any

### Reproduction

https://undocs.pages.dev/

### Describe the bug

When switching to light mode, the colors are kinda thrown off, prob related to recent merge.
 
![CleanShot 2024-02-22 at 16 52 55@2x](https://github.com/unjs/undocs/assets/6619884/f121d7d9-b9a3-4cd1-96d8-6c2729d601a8)

**Comment by pi0** [comment]
Thanks for notice.

I set default to dark because there were issues with light mode (was it for you or had to manually switch to light?)

But this is new.

I am probably already too late for my other works that can not work on it if are free feel free to check ❤️

**Comment by cpreston321** [comment]
This is if I set manually switch to light. I can see what's going on and check it out.

**Comment by pi0** [comment]
Downgrade fixed it (https://github.com/unjs/undocs/pull/60)
