### ISSUE TITLE
Theme and Search button in new docs

### ISSUE THREAD

**Issue by moshetanzer** [unjs/undocs#69]
### Environment

Docs

### Reproduction

The nitro website

### Describe the bug

Hi @pi0,

lovely new docs!

However on mobile (IOS tested both chrome and safari) when clicking to change theme it seems like you have to click once to make “active” and then again to make popover open. With Search just crazy lag from time of click to search opening. 
button links leaving website seem to work fine. 

Thanks!

**Comment by moshetanzer** [comment]
Sorry should have opened here🙈 - seems to be an issue across all undocs.

**Comment by pi0** [comment]
No worries moved to the right repo. I also faced issue but sadly no chance to investigate. You are welcome to contribute ❤️

**Comment by moshetanzer** [comment]
@pi0 opened this pr https://github.com/nuxt/ui/pull/1415 doubt it is best way to do it - though fixes it

**Comment by moshetanzer** [comment]
@pi0 this issue has been solved on latest release of Nuxt UI can we update this package and rest of ecosystem ❤️
