### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by moshetanzer** [unjs/undocs#77]
Hi @pi0,

Did you not add a loading indicator on purpose. Just find that buttons and links on mobile are too slow and you never know if the click routed (so too sometimes on desktop).

Am just thinking of a basic minimalistic one just as an indicator - instant feedback for UX. 

Am happy to create PR just don't want to do it if this a design decision. 

Keep it up🚀🚀

**Comment by moshetanzer** [comment]
Yip. That was plan just wanted to make sure that it wasn't left out on purpose.

**Comment by pi0** [comment]
Surely PR welcome 👍🏼
