### ISSUE TITLE
Cannot start dev server with pnpm

### ISSUE THREAD

**Issue by yuusheng** [unjs/undocs#97]
### Environment

pnpm@8.15.4
Node@20.11.0
MacOS Sonoma 14.2 beta

### Reproduction

```bash
pnpm dlx giget gh:unjs/undocs/template docs
cd docs
pnpm i
```

### Describe the bug

When executing `pnpm dev`,  it complains that `Cannot start nuxt:  Cannot find module nuxt`
<img width="1126" alt="image" src="https://github.com/unjs/undocs/assets/64511565/7ed1f4c3-9c22-49b2-a9a0-c732cf03fa6d">

And when using `bun`, it works well.

This is also reported in https://github.com/unjs/undocs/issues/71

**Comment by pi0** [comment]
Hi. Yes i'm aware of this issue and it might need changes in nuxi CLI because how specific usage we have with undocs, and it not a priority (undocs is tested and used with `bun` in unjs repos).

May I ask why you need pnpm specifically?

**Comment by yuusheng** [comment]
Personally, I don't need pnpm specifically. But in many use cases, people will use pnpm as their default package manager because of its speed and reliability. It's quite confusing when facing this kind of error. This issue can also be recorded when people face this error and search for a result in the issues list.

**Comment by pi0** [comment]
Yes, i also do use pnpm quite often and it is default for unjs repos. Only this is currently an internal tool and choosing but was intentional to both develop faster and also avoid conflicting with pnpm workspaces.

**Comment by yuusheng** [comment]
Oh, I see!

I find Undocs incredibly cool and believe it has the potential for widespread use! I will give a hand to make it better

**Comment by pi0** [comment]
Thank you so much! If you probably noticed branding is already [splitted](https://github.com/unjs/undocs/tree/main/app/.unjs)

But it probably takes more time and patience until we reach to a point that make undocs usable generally for everyone.

Until then let's be lean toward one runtime to test undocs and keep with `bun`. Looking forward for your contributions!
